### ISSUE TITLE
Add me as a collaborator?

### ISSUE THREAD

**Issue by cmcaine** [JuliaWeb/Mux.jl#121]
I'd quite like to get this package to v1 and it would be convenient to be able to add labels to issues and maybe manage milestones, releases, etc.

**Comment by cmcaine** [comment]
Thank you :)

**Comment by cmcaine** [comment]
I've been added as a collaborator (thanks!) but I still don't have permission to manage issues or PRs (I cannot label or close them) and I cannot create project boards or milestones.

Could someone check in on the permissions tab or something?

**Comment by jpsamaroo** [comment]
I just upgraded you to Triage status, which should be enough to let you manage issues and PRs.
