### ISSUE TITLE
Migrating from Meddle.jl to Mux.jl

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/Mux.jl#13]
Hi there,
This is a request for help rather than an issue with Mux.jl. Apologies if this belongs somewhere else.

I am trying to migrate example 4 in [this project](https://bitbucket.org/jocklawrie/skeleton-webapp.jl/src/fbfe6b045bb1/apps/?at=master) from Meddle.jl to Mux.jl. The Meddle version is in `example_4_middleware_MEDDLE` and the Mux version is in  `example_4_middleware`, still under development.

As you can see in `example_4_middleware/main_middleware.jl` I'm building up to it and I'm having a little trouble understanding what's going on. What should the 2nd argument to `Page()` be? A function that takes a request and returns a response?

FYI - it may or may not help to know that both examples are functionally the same as example_3_servefiles, only the latter does not use middleware at all.

Cheers,
Jock

**Comment by jpsamaroo** [comment]
@JockLawrie I'm not sure if you still need assistance with this, but I think it would best if you close this issue and request assistance on Discourse or Slack, where you are more likely to receive help from the community.
