### ISSUE TITLE
Is there WSS option in Mux v1.0.1?

### ISSUE THREAD

**Issue by disleyland** [JuliaWeb/Mux.jl#149]
I've only been able to get WSS working if Mux is downgraded to v0.7.6 and using WSS server support via WebSockets.jl.   Noticed that I cannot even upgrade to Mux 1.0.1 unless the WebSockets.jl package is removed entirely and Mux installed a fresh...which begs the question here of whether there is new syntax to access WSS capabilities I'm just not aware of, or I must actually stick with 0.7.6 for now.  

Any help?

**Comment by cmcaine** [comment]
WSS is supported. Check the SSL/TLS section of the tests for a complete example. Websockets.jl was merged into HTTP.jl, so you don't need or want it as a separate package.
