### ISSUE TITLE
WebSockets example in README is slightly broken

### ISSUE THREAD

**Issue by hsseung** [JuliaWeb/Mux.jl#154]
It works if you change `import Mux.WebSockets` to `using Mux.WebSockets`.

Otherwise you get an error message that `send` is not defined.

Also the function `websocket_example` needs to be defined before the server app.

**Comment by cmcaine** [comment]
Thanks! Fixed!

**Comment by Benoit9** [comment]
In the server code, I need both statements:

```
using Mux.WebSockets
using Mux
```

Otherwise I get `send not defined` when the client connects.
