### ISSUE TITLE
notfound() responds with 200 error code

### ISSUE THREAD

**Issue by dls** [JuliaWeb/Mux.jl#16]
Cool library. It looks like notfound() isn't setting the status code though.

```julia
using Mux

@app test = (
  Mux.defaults,
  page(respond("<h1>Hello World!</h1>")),
  Mux.notfound())

serve(test)
```

```
curl -v http://127.0.0.1:8000/404_plz
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /nod HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 9
< Content-Type: text/html; charset=utf-8
< Date: Sat, 31 Oct 2015 08:12:47
< Content-Language: en
< Server: Julia/0.4.0
<
* Connection #0 to host 127.0.0.1 left intact
Not found
```

After some digging, it looks like this is because of a (mis?)use of the Lazy.jl @d macro:

```julia
# from Mux.jl/src/examples/basic.jl
notfound(s = "Not found") = mux(status(404), respond(s))

# from Mux.jl/src/basics.jl
reskey(k, v) = post(res -> merge!(res, @d(k=>v)))

status(s) = reskey(:status, s)
```

Which unfortunately seems to do something other than what's intended by that line...

```julia
julia> k = 10
10

julia> @d(k => 1)
Dict{Any,Any} with 1 entry:
  :k => 1
```

I can fork and define ```reskey(k, v) = post(res -> merge!(res, Dict(k=>v)))``` if you'd like. I have to admit I'm confused about what precisely @d is intended to do, so I'm asking first.

**Comment by rohitvarkey** [comment]
The `@d` macro is used to provide backwards compatibility for the `Dict` syntax with 0.3. So that is probably not which is causing this.

**Comment by dls** [comment]
Ahh, okay, I'm not sure what to change then. I will say @d doesn't *seem* to match the ```Dict``` syntax... but that probably means there's something I'm missing. As you think best.

```julia
julia> using Lazy

julia> k = "test"
"test"

julia> @d(k => 3)
Dict{Any,Any} with 1 entry:
  :k => 3

julia> Dict(k => 3)
Dict{ASCIIString,Int64} with 1 entry:
  "test" => 3
```

**Comment by one-more-minute** [comment]
Ah yes, good spot – since 0.4 was released I changed `@d` to auto-keyify its arguments for convenience. Changing `@d` to just `d` should do the trick.

**Comment by dls** [comment]
Closing this down, since the fix is merged.
