### ISSUE TITLE
blocking serve

### ISSUE THREAD

**Issue by andrewrothstein** [JuliaWeb/Mux.jl#18]
is there a blocking version of the serve function? when I launch my web server I want to be able to leave it running forever. I'm happy to put a 

serve(app, port)
waitforever()

into my app but I think it would be useful to have a serve_sync function. what do you think?
I'm happy to raise a pull request if you think this is a good idea.

**Comment by one-more-minute** [comment]
Does `@sync serve(,,,)` do the trick for you?

**Comment by andrewrothstein** [comment]
thought a little bit more about it and I think the right change is to make serve return the task

function serve(s::Server, port = default_port)
return @async @errs run(s, port)
end

then I can
wait(serve(app, port))

how about a PR for that? feels more consistent with the concurrency model than your proposal.

**Comment by andrewrothstein** [comment]
I raised a PR for my second idea as https://github.com/JuliaWeb/Mux.jl/pull/19

**Comment by one-more-minute** [comment]
One of the main advantages of the current approaches is that you can do things like

```julia
@async begin
  serve(...)
  serve(...)
end
```
in order to setup and wait for multiple servers. You could certainly do this by setting up a task and `wait`ing on it, but by then you're essentially just reimplementing `@sync` and `@async` by hand.

**Comment by essenciary** [comment]
I was having the same question - @sync does the trick, thanks. 
Maybe the README can be updated to include examples of running it as an app server? (so not via REPL).

**Comment by andrewrothstein** [comment]
Yeah, apologies for not closing this. the sync macro does the trick in exactly the way @one-more-minute mentioned

**Comment by one-more-minute** [comment]
Examples for the readme would be welcome if you're willing to put something together. Running from a script isn't something I've done as much myself, because I usually just start a REPL in a screen session and boot the server from there.

**Comment by essenciary** [comment]
Sorry, I missed the updates. Sure, I'll add a simple example in the README, per the above discussion.
