### ISSUE TITLE
Need help to find all the paramteres of Request type.

### ISSUE THREAD

**Issue by sarvjeetsinghghotra** [JuliaWeb/Mux.jl#37]
Can someone please tell how to find all the params of a `request` ? Like `req[:path]`, `req[:cookie]` etc.

I looked [here](https://github.com/JuliaWeb/HttpCommon.jl/blob/master/src/HttpCommon.jl#L38) but I didn't find `user`, `cookies` etc shown [here](https://github.com/JuliaWeb/Mux.jl#apps-and-middleware). So is there a way to find about all of them. I am trying to contribute by writing routing middlewares.

**Comment by phelipe** [comment]
I think the requests are made using
https://github.com/JuliaWeb/HttpCommon.jl/blob/master/src/HttpCommon.jl
maybe the link will help you in something.

I'm using Merly.jl now, I found it simpler and more documented.
https://github.com/codeneomatrix/Merly.jl
