### ISSUE TITLE
Seems  unnecessarily using HttpServer in basic.jl  

### ISSUE THREAD

**Issue by sarvjeetsinghghotra** [JuliaWeb/Mux.jl#42]
I think `HttpServer` is not required in basic.jl, [here](https://github.com/JuliaWeb/Mux.jl/blob/master/src/basics.jl#L1). I ran the runtests.jl file in test folder, it worked fine even without using `HttpServer` in basic.jl file.

**Comment by jpsamaroo** [comment]
I believe this issue is no longer relevant to current Mux (at least not on master, there are no traces of HttpServer being used any longer), everything is now using HTTP.jl.
