### ISSUE TITLE
add @sync to example

### ISSUE THREAD

**Issue by bitmage** [JuliaWeb/Mux.jl#43]
When I run the first example in a Julia file, Julia exits before the web server starts.  I think the example should be amended:

```julia
@sync serve(test)
```

Notably, without this it doesn't print out any sort of message.  I had to read the mux code to find out what was going on.

**Comment by sina-masoud-ansari** [comment]
Possibly related to #73, `@sync serve(test)` doesn't seem to work in Mux v0.7.1, `fetch(serve(test))` does however.
