### ISSUE TITLE
Server on 0.0.0.0

### ISSUE THREAD

**Issue by mrkimo1998** [JuliaWeb/Mux.jl#44]
```julia
using Mux

@app test = (
  Mux.defaults,
  page(respond("<h1>Hi</h1")),
  Mux.notfound())
@sync serve(test, port=1234)
```

Only spawns a Server on 0.0.0.0:1234
how is that changeable ? host=127.0.0.1 in the serve doesnt work

**Comment by catethos** [comment]
Looking at the source code [here](https://github.com/JuliaWeb/Mux.jl/blob/master/src/server.jl#L44)

```julia
function serve(s::Server, port = default_port; kws...)
  @async @errs run(s; port = port, kws...)
  return
end
```

The `serve` function takes in extra keyword arguments that pass into the `run` function in [HTTPServer.jl ](https://github.com/JuliaWeb/HttpServer.jl). So we can pass in the host like this

```julia
using HttpServer
using Mux

@app test = (
  Mux.defaults,
  page(respond("<h1>Hi</h1")),
  Mux.notfound())
@sync serve(test, port=1234,host=IPv4(127,0,0,1))
```

**Comment by cmcaine** [comment]
This can now be done with `serve(app, host, port)`. This can be closed.
