### ISSUE TITLE
Configure rate_limits

### ISSUE THREAD

**Issue by nico202** [JuliaWeb/Mux.jl#77]
Hi, I cannot figure out how to configure rate limits, any suggestions? I think it's the HTTP.listen `rate_limits` param, but how do I set it from the Mux.serve?
Thanks

**Comment by hustf** [comment]
I am not really familiar with this package, but recently discovered how it actually works.

https://github.com/JuliaWeb/WebSockets.jl/issues/124

There is a test file in that package for throttling. A pr for capping the maximum rate would be welcome.

**Comment by cmcaine** [comment]
Mux.serve passes unknown keyword arguments on to HTTP.serve, so you can do:

```
serve(app; rate_limit=10//1)
```

To set a rate limit of 10 connections per second per client IP address.

Added docstrings to clear up keyword behaviour.
