### ISSUE TITLE
Cannot disable full log in stdout

### ISSUE THREAD

**Issue by houd1ni** [JuliaWeb/Mux.jl#79]
The app, no matter configured or not, emits "info" on each request. It slows down response time while testing it and wastes log, that must be used for other stuff.

**Comment by hustf** [comment]
You probably know about ending lines with ; when playing around with defintions.

Given that the Julia web stack is a hierarchy of dependencies, we need to be able to adapt or suppress messages from further down the stack.

To find the actual source of some REPL output can be a bit tricky. It may require that you catch all output and add a header.
 
Here's an example I believe the following can be adapted for your context. There are some further examples of suppressing and adapting output in WebSockets.jl.

```
using Logging
import Logging.shouldlog
function shouldlog(::ConsoleLogger, level, _module, group, id)
    if _module == Mux.HTTP.Servers
        if level == Logging.Warn || level == Logging.Info
            return false
        else
            return true
        end
    else
        return true
    end
end
```

**Comment by houd1ni** [comment]
@hustf  Thanx, I'll try this.

Of course, I know, that most of any language library has a lot of deps. But in most languages, log level is either configurable or even get destroyed by minifier (JavaScript included). By default, for sure, in production use (env variable?) this should be disabled. Or is there any advantage by using such things as webservers in REPL? 😆 

I also know that the lib has only one dependency -- HTTP. So, I believe, the real problem has to be found there.

**Comment by hustf** [comment]
The Julia webstack libraries I know are not up to par for "production use", but to my knowledge they are the fastest solution when interfacing with Julia processes (and possibly other things, but I would go for user-friendliness and stack-overflow coverage in that case). In core packages, user-friendliness will  be sacrificed for speed, stability and transparency. More user-facing code can add user-friendliness. Even if those users are other package developers.

Unfortunately, Logging.jl is a very recent addition to the standard library and therefore not widely used. This is very likely to improve if we keep submitting small issues and pull requests, e.g. replacing @info with @debug or adding examples.

By the way, Mux.jl has more dependencies, see 'REQUIRE'. And I don't favour using environment variables for controlling the output, but it's very nice if the setting can be changed while a server is running.

**Comment by tjlittle** [comment]
In case it's not clear from the thread, @hustf's solution works. At least it did for me.

**Comment by jpsamaroo** [comment]
Mux.jl does not contain any `at-info` or `at-debug` macros; it is HTTP.jl that does. The only uses of `print`/`println` are in error cases, which should probably be replaced with `@error` or `@warn`, as appropriate.
