### ISSUE TITLE
Move WebIO integration into this package.

### ISSUE THREAD

**Issue by travigd** [JuliaWeb/Mux.jl#95]
:^)

**Comment by jpsamaroo** [comment]
Can you give a brief overview of what functionality needs adding to Mux? Will we need to add new dependencies to make this work? And will it be generic enough that other packages can make use of the new functionality?

**Comment by travigd** [comment]
This is currently what we do to make it work: https://github.com/JuliaGizmos/WebIO.jl/blob/master/src/providers/mux.jl

Here's a PR where I moved the integration into Blink: https://github.com/JuliaGizmos/Blink.jl/pull/201/files

So, roughly,
* Define a connection type that extends `WebIO.AbstractConnection`
* Make sure `Mux.Response` works for WebIO nodes.

The last point is kind of tricky because ideally you'd want arbitrary things that are WebIO-renderable to just work without defining additional methods.

https://github.com/JuliaWeb/Mux.jl/blob/7156067ac7beff6af93339287a83548bc351db68/src/basics.jl#L47

The issue is that we don't want HTML strings to be processed via WebIO, so maybe that would become something like...
```julia
Response(s::AbstractString) = HTTP.Response(s)
Response(x) = HTTP.Response("""
<html>
<head>
<script src=...>
</head>
<body>
$(stringmime(MIME("text/html"), WebIO.render(x)))
</body>
</html>
""")
```

Ping @shashi

**Comment by travigd** [comment]
We'd also have to move the JS stuff into Mux. Or just make it work via the existing generic-http-provider which will stay in WebIO (this means you won't have to deal with managing JS bundles in this repo which is a **pain**).

**Comment by jpsamaroo** [comment]
I would personally prefer if this package doesn't accrue external dependencies like node.js, but if it's just a small bit of plain JS and glue code to make interop less cumbersome, then I won't object.

Would you be willing to make the PR?

**Comment by travigd** [comment]
It wouldn't be a runtime dependency but rather a build-time one. You'd probably need Webpack unless you want to use modules: https://caniuse.com/#search=modules.

**Comment by jpsamaroo** [comment]
Built-time or runtime, I'd like to avoid both. This package has generally been quite small, simple, and pure Julia (as far as I can tell anyway), and it would be nice to keep it that way.

Of course, I'll defer to Shashi on the final decision, but I wanted to make my preferences known.

**Comment by travigd** [comment]
Whoops I didn't quite finish my comment.

> It wouldn't be a runtime dependency but rather a build-time one. You'd probably need Webpack unless you want to use modules: https://caniuse.com/#search=modules.

So I think using the generic http provider would be good™.

I don't **really** want to make the PR but I might get to it eventually (I'd be very happy to consult/answer questions though!). It's fairly low-priority for me right now because it **works**, but when we go to release WebIO 1.0 we'll want to do this because it'll allow us to clean up a lot of API concerning registering things as renderable in Mux.

**Comment by shashi** [comment]
Yeah we definitely shouldn't install NodeJS or typescript compiler to allow people to install Mux. :-)
